#!/usr/bin/env python3
"""Add shell-completion installation to formulae generated by dist.

dist renders each formula from a fixed template and force-pushes the result on
every release, so a hand-edit survives exactly until the next version. Its
Homebrew publisher exposes no template override and no post-install hook: the
template copies non-doc files into pkgshare and stops, which leaves
`brew install` with a working binary and dead completion scripts nobody sources.

Run from the tap root. Prints the files it changed, one per line, to stdout;
diagnostics go to stderr. Idempotent — a formula that already has the call is
left alone, so re-running is free.
"""

import pathlib
import re
import sys

# Homebrew runs the installed binary once per shell and files each output under
# the directory that shell already searches. It appends the shell name to the
# arguments, so this invokes `<binary> completions <shell>` — which is the CLI's
# existing subcommand, needing no formula-specific flag.
MARKER = "generate_completions_from_executable"

# The call site inside `def install`, which is where the addition belongs. The
# leading-whitespace group deliberately excludes `def install_binary_aliases!`
# further up the file: that line has `def ` between the indent and the name.
ANCHOR = re.compile(r"^([ \t]+)install_binary_aliases!$", re.M)


def patch(path: pathlib.Path) -> bool:
    """Insert the completion call. True if the file was modified."""
    src = path.read_text()
    if MARKER in src:
        return False

    anchor = ANCHOR.search(src)
    if not anchor:
        print(f"::warning::{path}: no dist anchor, skipping", file=sys.stderr)
        return False

    # `bin.install "name"` is the authoritative executable name. The formula
    # class name is not: dist derives it by camel-casing, so `my-tool` becomes
    # `MyTool` with no way back to the hyphen.
    binary = re.search(r'bin\.install\s+"([^"]+)"', src)
    if not binary:
        print(f"::warning::{path}: installs no binary, skipping", file=sys.stderr)
        return False

    indent = anchor.group(1)
    addition = "\n".join(
        [
            "",
            f"{indent}# Added by .github/workflows/add-completions.yml because the",
            f"{indent}# formula generator has no hook for installing completions.",
            f'{indent}{MARKER}(bin/"{binary.group(1)}", "completions")',
        ]
    )
    path.write_text(src[: anchor.end()] + addition + src[anchor.end() :])
    return True


def main() -> int:
    formulae = sorted(pathlib.Path("Formula").glob("*.rb"))
    if not formulae:
        print("::error::no formulae found; is this the tap root?", file=sys.stderr)
        return 1
    for path in formulae:
        if patch(path):
            print(path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
